---
apiVersion: v1
kind: Namespace
metadata:
  name: product-lists
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: dockersamples_product-lists
spec:
  type: LoadBalancer
  selector:
    app: product-lists-web
  ports:
    - protocol: TCP
      port: 5735
      targetPort: http
